# Generated by Django 5.2.4 on 2026-05-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionrecord',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
