# Generated by Django 5.2.4 on 2026-05-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_remove_emissionrecord_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
