# Generated by Django 5.2.4 on 2026-05-29 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_emissionrecord_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionrecord',
            name='amount',
        ),
    ]
